{{- $releaseNamespace := .Release.Namespace -}}
{{- $releaseName := "icte" -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "noc-ran.fullname" . }}
  labels:
    {{- include "noc-ran.labels" . | nindent 4 }}
spec:
{{- if .Values.global.route.with_ns }}
  host: {{ $releaseName }}-ui-{{ $releaseNamespace }}.{{ .Values.global.ingress}} 
{{- else}}
  host: {{ $releaseName }}-ui-{{ .Values.global.route.name_in_url }}.{{ .Values.global.ingress}}  
{{- end }}
  path: /ran
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "noc-ran.fullname" . }}
    weight: 100
  wildcardPolicy: None
